import 'package:flutter/material.dart';

final List<Map<String, dynamic>> percentageCalculatorsMeta = [
  {
    'name': 'Percentage of Number',
    'short': 'Value of %',
    'desc': 'Calculate the value of X% of a number.',
    'formula': 'Result = Number × Percentage ÷ 100',
    'icon': Icons.calculate_rounded,
    'input1Label': 'Number',
    'input1Hint': 'Enter base number',
    'input2Label': 'Percentage (%)',
    'input2Hint': 'Enter percentage rate',
  },
  {
    'name': 'What Percentage?',
    'short': '% of Value',
    'desc': 'Find what percentage one number is of another.',
    'formula': 'Percentage = (Value ÷ Total Value) × 100',
    'icon': Icons.query_stats_rounded,
    'input1Label': 'Value',
    'input1Hint': 'Enter part value',
    'input2Label': 'Total Value',
    'input2Hint': 'Enter total value',
  },
  {
    'name': 'Percentage Increase',
    'short': '% Increase',
    'desc': 'Find the percentage growth from old value to new value.',
    'formula': 'Increase % = ((New − Old) ÷ Old) × 100',
    'icon': Icons.trending_up_rounded,
    'input1Label': 'Old Value',
    'input1Hint': 'Enter starting value',
    'input2Label': 'New Value',
    'input2Hint': 'Enter ending value',
  },
  {
    'name': 'Percentage Decrease',
    'short': '% Decrease',
    'desc': 'Find the percentage shrink from old value to new value.',
    'formula': 'Decrease % = ((Old − New) ÷ Old) × 100',
    'icon': Icons.trending_down_rounded,
    'input1Label': 'Old Value',
    'input1Hint': 'Enter starting value',
    'input2Label': 'New Value',
    'input2Hint': 'Enter ending value',
  },
  {
    'name': 'Percentage Difference',
    'short': '% Diff',
    'desc': 'Find the percentage difference between two values.',
    'formula': 'Difference % = (|Value 1 − Value 2| ÷ Average) × 100',
    'icon': Icons.difference_rounded,
    'input1Label': 'Value 1',
    'input1Hint': 'Enter first value',
    'input2Label': 'Value 2',
    'input2Hint': 'Enter second value',
  },
  {
    'name': 'Profit Percentage',
    'short': 'Profit %',
    'desc': 'Find profit amount and profit percentage from Cost and Selling Prices.',
    'formula': 'Profit % = ((SP − CP) ÷ CP) × 100',
    'icon': Icons.trending_up_rounded,
    'input1Label': 'Cost Price (CP)',
    'input1Hint': 'Enter cost price',
    'input2Label': 'Selling Price (SP)',
    'input2Hint': 'Enter selling price',
  },
  {
    'name': 'Loss Percentage',
    'short': 'Loss %',
    'desc': 'Find loss amount and loss percentage from Cost and Selling Prices.',
    'formula': 'Loss % = ((CP − SP) ÷ CP) × 100',
    'icon': Icons.trending_down_rounded,
    'input1Label': 'Cost Price (CP)',
    'input1Hint': 'Enter cost price',
    'input2Label': 'Selling Price (SP)',
    'input2Hint': 'Enter selling price',
  },
  {
    'name': 'Discount Calculator',
    'short': 'Discount',
    'desc': 'Calculate savings amount and final price after discount percentage.',
    'formula': 'Discount = Price × Discount % ÷ 100',
    'icon': Icons.local_offer_rounded,
    'input1Label': 'Original Price (₹)',
    'input1Hint': 'Enter original price',
    'input2Label': 'Discount (%)',
    'input2Hint': 'Enter discount percentage',
  },
  {
    'name': 'Markup Calculator',
    'short': 'Markup',
    'desc': 'Calculate markup cost and final selling price.',
    'formula': 'Selling Price = Cost + (Cost × Markup % ÷ 100)',
    'icon': Icons.add_business_rounded,
    'input1Label': 'Cost Price (CP) (₹)',
    'input1Hint': 'Enter cost price',
    'input2Label': 'Markup (%)',
    'input2Hint': 'Enter markup percentage',
  },
  {
    'name': 'Margin Calculator',
    'short': 'Margin %',
    'desc': 'Calculate profit margin percentage based on cost and selling price.',
    'formula': 'Margin % = ((SP − CP) ÷ SP) × 100',
    'icon': Icons.space_dashboard_rounded,
    'input1Label': 'Cost Price (CP) (₹)',
    'input1Hint': 'Enter cost price',
    'input2Label': 'Selling Price (SP) (₹)',
    'input2Hint': 'Enter selling price',
  },
  {
    'name': 'Percentage Change',
    'short': '% Change',
    'desc': 'Calculate percentage shift (growth/reduction) from old to new value.',
    'formula': 'Change % = ((New − Old) ÷ Old) × 100',
    'icon': Icons.compare_arrows_rounded,
    'input1Label': 'Old Value',
    'input1Hint': 'Enter initial value',
    'input2Label': 'New Value',
    'input2Hint': 'Enter revised value',
  },
  {
    'name': 'Commission Calculator',
    'short': 'Commission',
    'desc': 'Find commission earnings and remaining net amount.',
    'formula': 'Commission = Sale × Commission % ÷ 100',
    'icon': Icons.handshake_rounded,
    'input1Label': 'Sale Amount (₹)',
    'input1Hint': 'Enter total sale amount',
    'input2Label': 'Commission (%)',
    'input2Hint': 'Enter commission percentage',
  },
];
